refactor(structure): move files to /src folder
artsy/forque pull request #6
Opened 2022-03-23 17:53 UTC by damassi

This moves our sourcecode into an `/src` folder to better scope things.

2022-03-23 19:05 UTC, damassi commented on .eslintrc.js
> +    "testing-library/render-result-naming-convention": "off",
This rule is creeping into source-code

2022-03-24 03:17 UTC, anandaroop requested changes
Thanks for jumping in!

> * moves source code into `src` folder to better scope things
> * adds absolute path import support
> * adds `.vscode/settings.json` so that VSCode can pick up configurations and enforce them across developer environments
> * upgrades Next.js to latest (12.1)

🙌🏽 Yess to all this

> * colocates everything to match our other JS apps (page/app related components live with page/app folder; stories live with components alongside co-located tests, and so on)

This one is problematic because it is an anti-pattern in Next.js terms.

In every Next app I've seen, the `/pages` directory is strictly lightweight [Page components](https://nextjs.org/docs/basic-features/pages) that make use of their built-in conventions for [filesystem-based routing](https://nextjs.org/docs/routing/introduction). (I'd say this is part of the delight of using Next).

Everything else tends to be imported from a `/components` directory.

Notably, this is true of [their docs](https://nextjs.org/docs/basic-features/layouts) as well as their [example apps](https://github.com/vercel/next.js/tree/canary/examples) — see https://github.com/vercel/next.js/tree/canary/examples/with-stripe-typescript for one of the more fleshed out examples.

Having anything other than routable pages under the `/pages` directory will cause problems such as:

- Inadvertently bundling and exposing all those files as URLs (which will generally be broken links)

  Even in this PR, if you fire up the dev server you'll find that you can "browse" to http://localhost:3000/artists/dedupe/components/list/__tests__/ArtistList.spec

- Increasing build times, since Next is interpreting each of those files nested under `/pages` as a reachable URL that might need to have data injected at build time for SSG, ISR etc

So we'll definitely want to walk this commit back, and some new conventions / developer education will certainly be in order.

2022-03-24 03:39 UTC, damassi commented
> This one is problematic because it is an anti-pattern in Next.js terms.

This is not a fixed thing in Next and Next.js accommodates all! It might not be a "convention" in terms of the examples, but that's because examples are by nature very small and don't operate at scale. 

For something like a mono-admin such as this, we'll want to keep things as close to colocated as possible for organizational reasons and for that, we can use next's `pageExtension` prop: 

https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions#including-non-page-files-in-the-pages-directory

2022-03-24 03:55 UTC, anandaroop commented
Mind blown! Good on Next, yet again.

My googling skills were inadequate to finding that page the docs. I tried so many search terms, lol.

That's good to know about. But we do still need to configure that right? (See my comment about tests currently being exposed)

2022-03-24 03:56 UTC, damassi commented
On it now 🙏

2022-03-24 04:41 UTC, anandaroop commented
Nice, that fixes the exposed URLs as well as (presumably) by build-time concerns 🎉

2022-03-24 04:46 UTC, damassi commented
Yeah, now rather than a few new conventions / requirements we'd need to spread around as well as some dangerous conditions we'd need to guard against in PR review -- namely, unintentional exposure -- it's just one: a viewable "page" must contain `.page.tsx` in the name, which is arguably clearer as it makes things quite unambiguous.

2022-03-24 04:47 UTC, anandaroop commented
Seeing a couple small regressions involving Jest and Storybook. Looks like quick fixes — I'll push up a commit.

2022-03-24 04:50 UTC, anandaroop commented
All set now, we'd have caught wind of that sooner if CI was hooked up. That's coming soon, on the #product-velocity todo list, I'm pretty sure.

2022-03-24 04:51 UTC, anandaroop approved these changes

2022-03-24 04:53 UTC, merged